default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rent_a_car_development
  username: megicelik
  password: 123456

test:
  <<: *default
  database: rent_a_car_test
  username: megicelik
  password: 123456

production:
  <<: *default
  database: rent_a_car_production
  username: megicelik
  password: 123456
